export type ClassData = {
    code : string // "30003",
    type : string // "基礎",
    category : string // "数理科学",
    semester : string // "S1",
    periods : string[] // ["月2","水1"],
    classroom : string // "駒場5号館 523教室",
    titleJp : string // "数理科学基礎",
    lecturerJp : string // "逆井 卓也",
    titleEn : string // "Basics of Mathematical Sciences",
    lecturerEn : string // "SAKASAI Takuya",
    ccCode : string // "CAS-FC1871L1",
    credits : number // 2,
    detail : string // "科学・技術の礎となる数理科学の基礎的内容を学び...",
    schedule : string// "講義内容はおおむね以下の通りであるが, ...",
    methods : string //"講義形式であるが, 担当教員によっては適宜小テストやレポートを課すことが...",
    evaluation : string // "主としてS1ターム末に行われる定期試験によるが, ...",
    notes : string // "この科目は, S1タームを通じて各週2回の講義からなり, ...",
    class : string // "1年 理二三(1-7)",
    guidance : string // "なし",
    guidanceDate : string // "",
    guidancePeriod : string // "",
    guidancePlace : string // "",
    time : number // 90,
    timeCompensation : string // "授業の前または後に合計15分程度, 質疑応答の時間を設ける. ",
    targetClass : string[][] // [["s2_1","s3_1",(...),"s3_6","s2_7","s3_7"],[]],
    importance : string[][] // [["l1","l2","l3","s1","s2","s3"],[]],
    shortenedCategory : string // "基礎",
    shortenedEvaluation : string // "試験レポ平常",
    shortenedClassroom : string // "523"
}